In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel("C:/Users/admin/Downloads/axiom_vriksh24.xlsx", header=8)
df.head()

   PROJECT_NAME                  TIMESTAMP  PM2.5  PM10  TEMPERATURE  HUMIDITY
0  AXIOM VRIKSH  2026-03-24T00:10:07+05:30     39    66         30.9      48.8
1  AXIOM VRIKSH  2026-03-24T00:25:12+05:30     39    66         30.9      48.6
2  AXIOM VRIKSH  2026-03-24T00:40:15+05:30     43    72         30.9      48.1
3  AXIOM VRIKSH  2026-03-24T00:55:17+05:30     41    72         30.9      47.9
4  AXIOM VRIKSH  2026-03-24T01:10:20+05:30     40    68         30.8      48.5

In [2]:
#Converting from timestamp to datetime
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'], format='mixed')

In [3]:
#Set Index
df = df.set_index('TIMESTAMP')

In [4]:
#Resample data into 1hour batch
sensor_df = df.resample('1h').mean(numeric_only=True)

In [5]:
#Checking  Type of Index
print(type(df.index))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [6]:
#Interpolate: to replace with mode value of any  columns
sensor_df = sensor_df.interpolate(limit_direction='forward')

In [7]:
#Round-Of Data
sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']] = sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']].round(2)

In [8]:
#Reset Index
sensor_df = sensor_df.reset_index()

In [11]:
sensor_df.tail(10)

                   TIMESTAMP  PM2.5   PM10  TEMPERATURE  HUMIDITY
1  2026-03-24 01:00:00+05:30  37.50  63.00        30.72     48.35
2  2026-03-24 02:00:00+05:30  36.50  63.50        30.25     51.08
3  2026-03-24 03:00:00+05:30  36.25  61.75        29.80     56.52
4  2026-03-24 04:00:00+05:30  38.25  64.75        29.58     59.12
5  2026-03-24 05:00:00+05:30  43.50  78.25        29.32     61.50
6  2026-03-24 06:00:00+05:30  44.00  83.00        29.22     62.32
7  2026-03-24 07:00:00+05:30  50.00  96.00        29.35     63.80
8  2026-03-24 08:00:00+05:30  49.25  95.00        31.20     58.22
9  2026-03-24 09:00:00+05:30  41.00  77.75        33.52     47.38
10 2026-03-24 10:00:00+05:30  31.00  53.00        34.90     43.10