In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel("C:/Users/admin/Downloads/axiom_vriksh1.xlsx", header=8)
df.head()

,PROJECT_NAME,TIMESTAMP,PM2.5,PM10,TEMPERATURE,HUMIDITY
0,AXIOM VRIKSH,2025-07-09T15:56:43.334003+05:30,12,25,33.6,73.2
1,AXIOM VRIKSH,2025-07-09T15:57:13+05:30,15,23,33.6,73.2
2,AXIOM VRIKSH,2025-07-09T15:57:43+05:30,16,21,33.6,73.1
3,AXIOM VRIKSH,2025-07-09T15:58:13+05:30,14,28,33.6,73.3
4,AXIOM VRIKSH,2025-07-09T15:58:43+05:30,15,25,33.7,73.2

In [2]:
#Converting from timestamp to datetime
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'], format='mixed')

In [3]:
#Set Index
df = df.set_index('TIMESTAMP')

In [4]:
#Resample data into 1hour batch
sensor_df = df.resample('1h').mean(numeric_only=True)

In [5]:
#Checking  Type of Index
print(type(df.index))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [6]:
#Interpolate: to replace with mode value of any  columns
sensor_df = sensor_df.interpolate(limit_direction='forward')

In [7]:
#Round-Of Data
sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']] = sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']].round(2)

In [8]:
#Reset Index
sensor_df = sensor_df.reset_index()

In [9]:
sensor_df.head()

                  TIMESTAMP  PM2.5   PM10  TEMPERATURE  HUMIDITY
0 2025-07-09 15:00:00+05:30  14.71  24.57        33.61     73.20
1 2025-07-09 16:00:00+05:30  21.12  29.92        33.43     73.54
2 2025-07-09 17:00:00+05:30  21.13  29.92        33.43     73.54
3 2025-07-09 18:00:00+05:30  21.13  29.92        33.43     73.53
4 2025-07-09 19:00:00+05:30  21.13  29.92        33.43     73.52

In [43]:
#Weather Data 
weather_df = pd.read_excel("C:/Users/admin/Downloads/weather_data_birwadi_mahad.xlsx", header=16)
weather_df

,From Date,To Date,RH,WS,WD,SR,RF,AT,NO2,Ozone
0,13-08-2025 00:00,13-08-2025 01:00,70.87,2.06,204.50,0.00,0.0,26.19,11.21,14.96
1,13-08-2025 01:00,13-08-2025 02:00,70.82,1.47,234.78,0.00,0.0,26.13,11.04,14.61
2,13-08-2025 02:00,13-08-2025 03:00,70.93,2.18,205.64,0.00,0.0,26.26,11.36,16.14
3,13-08-2025 03:00,13-08-2025 04:00,71.05,1.73,207.66,0.00,0.2,26.39,15.19,14.63
4,13-08-2025 04:00,13-08-2025 05:00,70.90,1.85,207.88,0.00,0.0,26.23,17.10,11.88
...,...,...,...,...,...,...,...,...,...,...
5121,14-03-2026 09:00,14-03-2026 10:00,71.53,1.31,123.37,225.97,0.0,31.08,49.69,49.54
5122,14-03-2026 10:00,14-03-2026 11:00,70.89,1.10,221.14,328.17,0.0,33.91,38.20,51.16
5123,14-03-2026 11:00,14-03-2026 12:00,69.21,1.95,212.03,425.88,0.0,36.07,15.91,50.53
5124,14-03-2026 12:00,14-03-2026 13:00,66.29,2.09,234.81,440.45,0.0,38.21,13.59,49.83
5125,14-03-2026 13:00,14-03-2026 13:31,64.08,2.59,217.03,222.60,0.0,38.83,11.29,53.94

In [11]:
#Remode To Date Columns
weather_df = weather_df.drop('To Date',axis=1)

In [12]:
weather_df.set_index('From Date')

                     RH    WS      WD      SR   RF     AT    NO2  Ozone
From Date
13-08-2025 00:00  70.87  2.06  204.50    0.00  0.0  26.19  11.21  14.96
13-08-2025 01:00  70.82  1.47  234.78    0.00  0.0  26.13  11.04  14.61
13-08-2025 02:00  70.93  2.18  205.64    0.00  0.0  26.26  11.36  16.14
13-08-2025 03:00  71.05  1.73  207.66    0.00  0.2  26.39  15.19  14.63
13-08-2025 04:00  70.90  1.85  207.88    0.00  0.0  26.23  17.10  11.88
...                 ...   ...     ...     ...  ...    ...    ...    ...
14-03-2026 09:00  71.53  1.31  123.37  225.97  0.0  31.08  49.69  49.54
14-03-2026 10:00  70.89  1.10  221.14  328.17  0.0  33.91  38.20  51.16
14-03-2026 11:00  69.21  1.95  212.03  425.88  0.0  36.07  15.91  50.53
14-03-2026 12:00  66.29  2.09  234.81  440.45  0.0  38.21  13.59  49.83
14-03-2026 13:00  64.08  2.59  217.03  222.60  0.0  38.83  11.29  53.94

[5126 rows x 8 columns]

In [13]:
#Replace From Date to TIMESTAMP
weather_df.rename(columns={'From Date':'TIMESTAMP'}, inplace=True)

In [14]:
weather_df = weather_df.set_index('TIMESTAMP')

In [15]:
#Making Timestamp same
sensor_df['TIMESTAMP'] = sensor_df['TIMESTAMP'].dt.tz_localize(None)
#print(sensor_df.columns)
#sensor_df.head()

In [16]:
print(weather_df.columns)

Index(['RH', 'WS', 'WD', 'SR', 'RF', 'AT', 'NO2', 'Ozone'], dtype='object')

In [17]:
weather_df.head()

                     RH    WS      WD   SR   RF     AT    NO2  Ozone
TIMESTAMP
13-08-2025 00:00  70.87  2.06  204.50  0.0  0.0  26.19  11.21  14.96
13-08-2025 01:00  70.82  1.47  234.78  0.0  0.0  26.13  11.04  14.61
13-08-2025 02:00  70.93  2.18  205.64  0.0  0.0  26.26  11.36  16.14
13-08-2025 03:00  71.05  1.73  207.66  0.0  0.2  26.39  15.19  14.63
13-08-2025 04:00  70.90  1.85  207.88  0.0  0.0  26.23  17.10  11.88

In [18]:
weather_df = weather_df.reset_index()

In [19]:
weather_df['TIMESTAMP'] = pd.to_datetime(
    weather_df['TIMESTAMP'],
    format='%d-%m-%Y %H:%M'
)

In [20]:
weather_df.head()

            TIMESTAMP     RH    WS      WD   SR   RF     AT    NO2  Ozone
0 2025-08-13 00:00:00  70.87  2.06  204.50  0.0  0.0  26.19  11.21  14.96
1 2025-08-13 01:00:00  70.82  1.47  234.78  0.0  0.0  26.13  11.04  14.61
2 2025-08-13 02:00:00  70.93  2.18  205.64  0.0  0.0  26.26  11.36  16.14
3 2025-08-13 03:00:00  71.05  1.73  207.66  0.0  0.2  26.39  15.19  14.63
4 2025-08-13 04:00:00  70.90  1.85  207.88  0.0  0.0  26.23  17.10  11.88

In [21]:
#Merge Data So our ML model can train
merged_df = pd.merge(sensor_df,weather_df, on="TIMESTAMP")

In [22]:
merged_df = merged_df.dropna()

In [23]:
merged_df.size

62426

FULL LSTM SEQUENCE MODEL (72 → 24)

In [24]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [25]:
#Select Features
features = [
    'PM2.5', 'PM10', 'TEMPERATURE', 'HUMIDITY',
    'WS', 'WD', 'RF', 'NO2', 'Ozone'
]

data = merged_df[features]

In [26]:
#Normalize Data
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

In [27]:
#Create Sequence
def create_sequences(data, window=72, horizon=24):
    X, y = [], []
    
    for i in range(len(data) - window - horizon):
        X.append(data[i:i+window])
        y.append(data[i+window:i+window+horizon, 0:2])  # PM2.5, PM10
    
    return np.array(X), np.array(y)

X, y = create_sequences(scaled_data)

In [28]:
#Train-Test Split
split = int(len(X) * 0.8)

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

In [29]:
#Build LSTM Model
from tensorflow.keras.layers import Input

model = Sequential([
    Input(shape=(72, X.shape[2])),

    LSTM(128, return_sequences=True),
    Dropout(0.2),

    LSTM(64),
    Dropout(0.2),

    Dense(32, activation='relu'),
    Dense(48)
])

In [30]:
#Compile Model
model.compile(
    optimizer='adam',
    loss='mse'
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [31]:
#Train Model
model.fit(
    X_train,
    y_train.reshape(y_train.shape[0], -1),
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test.reshape(y_test.shape[0], -1))
)

Epoch 1/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 15s 73ms/step - loss: 0.0013 - val_loss: 0.0110
Epoch 2/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 60ms/step - loss: 2.1436e-04 - val_loss: 0.0102
Epoch 3/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 10s 59ms/step - loss: 1.4868e-04 - val_loss: 0.0097
Epoch 4/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 1.3453e-04 - val_loss: 0.0100
Epoch 5/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 59ms/step - loss: 1.1932e-04 - val_loss: 0.0101
Epoch 6/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 60ms/step - loss: 1.0814e-04 - val_loss: 0.0095
Epoch 7/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 1.0382e-04 - val_loss: 0.0097
Epoch 8/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 59ms/step - loss: 9.2104e-05 - val_loss: 0.0095
Epoch 9/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 8s 66ms/step - loss: 8.9242e-05 - val_loss: 0.0099
Epoch 10/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 8s 66ms/step - loss: 8.3600e-05 - val_loss: 0.0098
Epoch 11/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 8.1891e-05 - val_loss: 0.0095
Epoch 12/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 61ms/step - loss: 7.6592e-05 - val_loss: 0.0096
Epoch 13/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 8.5289e-05 - val_loss: 0.0096
Epoch 14/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 11s 60ms/step - loss: 7.9307e-05 - val_loss: 0.0099
Epoch 15/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 11s 68ms/step - loss: 7.7856e-05 - val_loss: 0.0098
Epoch 16/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 7.7409e-05 - val_loss: 0.0103
Epoch 17/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - loss: 7.3155e-05 - val_loss: 0.0098
Epoch 18/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 60ms/step - loss: 7.1105e-05 - val_loss: 0.0098
Epoch 19/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 60ms/step - loss: 7.1715e-05 - val_loss: 0.0098
Epoch 20/20
118/118 ━━━━━━━━━━━━━━━━━━━━ 7s 62ms/step - loss: 6.5752e-05 - val_loss: 0.0098

In [32]:
#Predict
pred = model.predict(X_test)

# reshape back to (samples, 24, 2)
pred = pred.reshape(-1, 24, 2)
y_test = y_test.reshape(-1, 24, 2)

30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step

In [33]:
#Evaluate
mae_pm25 = mean_absolute_error(y_test[:,:,0].flatten(), pred[:,:,0].flatten())
mae_pm10 = mean_absolute_error(y_test[:,:,1].flatten(), pred[:,:,1].flatten())

print("PM2.5 MAE:", mae_pm25)
print("PM10 MAE:", mae_pm10)

PM2.5 MAE: 0.05296318036674696
PM10 MAE: 0.05436530690237891

In [34]:
#Convert to Work/Not
PM25_LIMIT = 100
PM10_LIMIT = 150

def decision(pm25, pm10):
    return 0 if (pm25 > PM25_LIMIT or pm10 > PM10_LIMIT) else 1

In [35]:
#Decision Accuracy
actual = []
predicted = []

for i in range(len(pred)):
    for t in range(24):
        actual.append(decision(y_test[i, t, 0], y_test[i, t, 1]))
        predicted.append(decision(pred[i, t, 0], pred[i, t, 1]))

from sklearn.metrics import accuracy_score, classification_report

print("Decision Accuracy:", accuracy_score(actual, predicted))
print(classification_report(actual, predicted))

Decision Accuracy: 1.0
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     22608

    accuracy                           1.00     22608
   macro avg       1.00      1.00      1.00     22608
weighted avg       1.00      1.00      1.00     22608

In [36]:
#Real-Time Prediction
# Take last 72 hours
last_72 = scaled_data[-72:]

# reshape for model
last_72 = last_72.reshape(1, 72, X.shape[2])

future = model.predict(last_72)

future = future.reshape(24, 2)

# Example: next day average PM
pm25_next = future[:,0].mean()
pm10_next = future[:,1].mean()

print("Tomorrow Avg PM2.5:", pm25_next)
print("Tomorrow Avg PM10:", pm10_next)

if decision(pm25_next, pm10_next):
    print("✅ CONTINUE WORK")
else:
    print("❌ STOP WORK")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
Tomorrow Avg PM2.5: 0.15048134
Tomorrow Avg PM10: 0.10852752
✅ CONTINUE WORK

Optimize Threshold for SAFE Construction

In [37]:
# Save full model
model.save("lstm_model.h5")

# Save scaler (VERY IMPORTANT)
import joblib
joblib.dump(scaler, "scaler.pkl")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

['scaler.pkl']

In [38]:
import os
print(os.getcwd())

C:\Users\admin\Site_Work_Prediction_ML_Model

In [41]:
print(os.listdir())

['.git', '.ipynb_checkpoints', 'app.py', 'Future Prediction Model.ipynb', 'lstm_model.h5', 'merged_df.csv', 'README.md', 'requirements.txt', 'scaler.pkl']

In [40]:
merged_df.to_csv("merged_df.csv", index=False)