In [75]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/admin/Downloads/analiza_group.csv", header=7)
df.head()

,project_name,TIMESTAMP,PM2.5,PM10,TEMPERATURE,HUMIDITY
0,ANALIZA GROUPS - DOMNIC CHARLIE DSOUZA,2025-12-01T00:00:06+05:30,141.0,238.0,23.1,64.1
1,ANALIZA GROUPS - DOMNIC CHARLIE DSOUZA,2025-12-01T00:00:36+05:30,139.0,237.0,23.1,63.8
2,ANALIZA GROUPS - DOMNIC CHARLIE DSOUZA,2025-12-01T00:01:06+05:30,139.0,237.0,23.1,63.4
3,ANALIZA GROUPS - DOMNIC CHARLIE DSOUZA,2025-12-01T00:01:36+05:30,142.0,233.0,23.1,63.1
4,ANALIZA GROUPS - DOMNIC CHARLIE DSOUZA,2025-12-01T00:02:06+05:30,149.0,254.0,23.1,62.5

In [76]:
#Converting from timestamp to datetime
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'], format='mixed')

In [77]:
#Set Index
df = df.set_index('TIMESTAMP')

In [78]:
#Resample data into 1hour batch
sensor_df = df.resample('1h').mean(numeric_only=True)

In [79]:
#Checking  Type of Index
print(type(df.index))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [80]:
#Interpolate: to replace with mode value of any  columns
sensor_df = sensor_df.interpolate(limit_direction='forward')

In [81]:
#Round-Of Data
sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']] = sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']].round(2)

In [82]:
#Reset Index
sensor_df = sensor_df.reset_index()

In [83]:
sensor_df.head()

                  TIMESTAMP   PM2.5    PM10  TEMPERATURE  HUMIDITY
0 2025-12-01 00:00:00+05:30  131.65  220.32        22.96     64.74
1 2025-12-01 01:00:00+05:30   83.14  129.32        23.18     57.50
2 2025-12-01 02:00:00+05:30   83.22  127.04        22.82     57.30
3 2025-12-01 03:00:00+05:30   81.54  127.00        22.97     52.64
4 2025-12-01 04:00:00+05:30   68.71  104.21        22.63     52.46

Weather Data

In [84]:
weather_df = pd.read_excel("C:/Users/admin/Downloads/Kherbadi_bandra_east.xlsx", header=16)
weather_df

,From Date,To Date,NO2,Ozone,CO,RH,WS,WD,SR,RF,AT
0,01-12-2025 00:00,01-12-2025 01:00,38.19,1.20,0.97,60.63,0.96,145.86,0.00,0.0,23.32
1,01-12-2025 01:00,01-12-2025 02:00,NaN,1.85,1.08,56.44,1.01,98.04,0.00,0.0,23.97
2,01-12-2025 02:00,01-12-2025 03:00,NaN,2.23,1.03,57.06,0.84,104.93,0.00,0.0,23.27
3,01-12-2025 03:00,01-12-2025 04:00,NaN,2.25,0.95,56.80,0.72,85.60,0.00,0.0,22.61
4,01-12-2025 04:00,01-12-2025 05:00,NaN,0.93,0.87,56.16,0.57,138.53,0.00,0.0,22.31
...,...,...,...,...,...,...,...,...,...,...,...
2719,24-03-2026 07:00,24-03-2026 08:00,15.06,1.03,0.60,69.04,0.83,262.67,27.77,0.0,27.28
2720,24-03-2026 08:00,24-03-2026 09:00,25.08,7.61,0.60,48.73,0.70,278.78,257.43,0.0,31.09
2721,24-03-2026 09:00,24-03-2026 10:00,38.61,12.15,0.60,39.27,0.44,240.84,460.62,0.0,34.17
2722,24-03-2026 10:00,24-03-2026 11:00,35.10,18.88,0.59,29.04,0.80,75.16,647.00,0.0,36.66
2723,24-03-2026 11:00,24-03-2026 11:45,34.06,29.52,0.59,27.73,0.23,69.78,709.85,0.0,38.13

In [85]:
#Remode To Date Columns
weather_df = weather_df.drop('To Date',axis=1)

In [86]:
weather_df.set_index('From Date')

                    NO2  Ozone    CO     RH    WS      WD      SR   RF     AT
From Date
01-12-2025 00:00  38.19   1.20  0.97  60.63  0.96  145.86    0.00  0.0  23.32
01-12-2025 01:00    NaN   1.85  1.08  56.44  1.01   98.04    0.00  0.0  23.97
01-12-2025 02:00    NaN   2.23  1.03  57.06  0.84  104.93    0.00  0.0  23.27
01-12-2025 03:00    NaN   2.25  0.95  56.80  0.72   85.60    0.00  0.0  22.61
01-12-2025 04:00    NaN   0.93  0.87  56.16  0.57  138.53    0.00  0.0  22.31
...                 ...    ...   ...    ...   ...     ...     ...  ...    ...
24-03-2026 07:00  15.06   1.03  0.60  69.04  0.83  262.67   27.77  0.0  27.28
24-03-2026 08:00  25.08   7.61  0.60  48.73  0.70  278.78  257.43  0.0  31.09
24-03-2026 09:00  38.61  12.15  0.60  39.27  0.44  240.84  460.62  0.0  34.17
24-03-2026 10:00  35.10  18.88  0.59  29.04  0.80   75.16  647.00  0.0  36.66
24-03-2026 11:00  34.06  29.52  0.59  27.73  0.23   69.78  709.85  0.0  38.13

[2724 rows x 9 columns]

In [87]:
#Replace From Date to TIMESTAMP
weather_df.rename(columns={'From Date':'TIMESTAMP'}, inplace=True)

In [88]:
weather_df = weather_df.set_index('TIMESTAMP')

In [89]:
#Making Timestamp same
sensor_df['TIMESTAMP'] = sensor_df['TIMESTAMP'].dt.tz_localize(None)
#print(sensor_df.columns)
#sensor_df.head()

In [90]:
print(weather_df.columns)

Index(['NO2', 'Ozone', 'CO', 'RH', 'WS', 'WD', 'SR', 'RF', 'AT'], dtype='object')

In [91]:
weather_df = weather_df.reset_index()

In [92]:
weather_df['TIMESTAMP'] = pd.to_datetime(
    weather_df['TIMESTAMP'],
    format='%d-%m-%Y %H:%M'
)

Merge both the data

In [93]:
#Merge Data So our ML model can train
merged_df = pd.merge(sensor_df,weather_df, on="TIMESTAMP")

In [94]:
merged_df = merged_df.dropna()

In [95]:
merged_df.size

31850

LSTM Model Prediction (72-24)

In [41]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [59]:
#Select Features
features = [
    'PM2.5', 'PM10', 'TEMPERATURE', 'HUMIDITY',
    'WS', 'WD', 'RF', 'NO2', 'Ozone'
]

data = merged_df[features]

In [60]:
#Normalize Data
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

In [61]:
#Create Sequence
def create_sequences(data, window=72, horizon=24):
    X, y = [], []
    
    for i in range(len(data) - window - horizon):
        X.append(data[i:i+window])
        y.append(data[i+window:i+window+horizon, 0:2])  # PM2.5, PM10
    
    return np.array(X), np.array(y)

X, y = create_sequences(scaled_data)

In [62]:
#Train-Test Split
split = int(len(X) * 0.8)

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

In [63]:
#Build LSTM Model
from tensorflow.keras.layers import Input

model = Sequential([
    Input(shape=(72, X.shape[2])),

    LSTM(128, return_sequences=True),
    Dropout(0.2),

    LSTM(64),
    Dropout(0.2),

    Dense(32, activation='relu'),
    Dense(48)
])

In [64]:
#Compile Model
model.compile(
    optimizer='adam',
    loss='mse'
)

In [65]:
#Train Model
model.fit(
    X_train,
    y_train.reshape(y_train.shape[0], -1),
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test.reshape(y_test.shape[0], -1))
)

Epoch 1/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 10s 83ms/step - loss: 0.0121 - val_loss: 0.0510
Epoch 2/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 62ms/step - loss: 0.0020 - val_loss: 0.0336
Epoch 3/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - loss: 0.0012 - val_loss: 0.0324
Epoch 4/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 68ms/step - loss: 0.0012 - val_loss: 0.0322
Epoch 5/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 62ms/step - loss: 9.6566e-04 - val_loss: 0.0314
Epoch 6/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 62ms/step - loss: 9.2223e-04 - val_loss: 0.0314
Epoch 7/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - loss: 9.0400e-04 - val_loss: 0.0340
Epoch 8/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 62ms/step - loss: 7.6064e-04 - val_loss: 0.0332
Epoch 9/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - loss: 7.3511e-04 - val_loss: 0.0317
Epoch 10/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 63ms/step - loss: 6.7890e-04 - val_loss: 0.0350
Epoch 11/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 59ms/step - loss: 5.8423e-04 - val_loss: 0.0349
Epoch 12/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 67ms/step - loss: 6.0775e-04 - val_loss: 0.0400
Epoch 13/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 5s 65ms/step - loss: 9.0840e-04 - val_loss: 0.0315
Epoch 14/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - loss: 9.1034e-04 - val_loss: 0.0286
Epoch 15/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - loss: 6.7991e-04 - val_loss: 0.0284
Epoch 16/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 5s 62ms/step - loss: 6.6182e-04 - val_loss: 0.0315
Epoch 17/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 66ms/step - loss: 6.9870e-04 - val_loss: 0.0315
Epoch 18/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 5s 62ms/step - loss: 5.9280e-04 - val_loss: 0.0298
Epoch 19/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 5.3354e-04 - val_loss: 0.0312
Epoch 20/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - loss: 5.5862e-04 - val_loss: 0.0307

In [66]:
#Predict
pred = model.predict(X_test)

# reshape back to (samples, 24, 2)
pred = pred.reshape(-1, 24, 2)
y_test = y_test.reshape(-1, 24, 2)

14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

In [67]:
#Evaluate
mae_pm25 = mean_absolute_error(y_test[:,:,0].flatten(), pred[:,:,0].flatten())
mae_pm10 = mean_absolute_error(y_test[:,:,1].flatten(), pred[:,:,1].flatten())

print("PM2.5 MAE:", mae_pm25)
print("PM10 MAE:", mae_pm10)

PM2.5 MAE: 0.07094894358812179
PM10 MAE: 0.07085571754419734

In [68]:
#Convert to Work/Not
PM25_LIMIT = 100
PM10_LIMIT = 150

def decision(pm25, pm10):
    return 0 if (pm25 > PM25_LIMIT or pm10 > PM10_LIMIT) else 1

In [69]:
#Decision Accuracy
actual = []
predicted = []

for i in range(len(pred)):
    for t in range(24):
        actual.append(decision(y_test[i, t, 0], y_test[i, t, 1]))
        predicted.append(decision(pred[i, t, 0], pred[i, t, 1]))

from sklearn.metrics import accuracy_score, classification_report

print("Decision Accuracy:", accuracy_score(actual, predicted))
print(classification_report(actual, predicted))

Decision Accuracy: 1.0
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     10464

    accuracy                           1.00     10464
   macro avg       1.00      1.00      1.00     10464
weighted avg       1.00      1.00      1.00     10464

In [70]:
#Real-Time Prediction
# Take last 72 hours
last_72 = scaled_data[-72:]

# reshape for model
last_72 = last_72.reshape(1, 72, X.shape[2])

future = model.predict(last_72)

future = future.reshape(24, 2)

# Example: next day average PM
pm25_next = future[:,0].mean()
pm10_next = future[:,1].mean()

print("Tomorrow Avg PM2.5:", pm25_next)
print("Tomorrow Avg PM10:", pm10_next)

if decision(pm25_next, pm10_next):
    print("✅ CONTINUE WORK")
else:
    print("❌ STOP WORK")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
Tomorrow Avg PM2.5: 0.0048752357
Tomorrow Avg PM10: 0.0067260973
✅ CONTINUE WORK

In [71]:
# Save full model
model.save("lstm_model2.h5")

# Save scaler (VERY IMPORTANT)
import joblib
joblib.dump(scaler, "scaler2.pkl")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

['scaler2.pkl']

In [96]:
merged_df.to_csv("merged_df2.csv", index=False)

In [73]:
import os
print(os.getcwd())

C:\Users\admin\Site_Work_Prediction_ML_Model

In [58]:
print(os.listdir())

['.git', '.ipynb_checkpoints', '24March Data Resample.ipynb', 'app.py', 'Future Prediction Model.ipynb', 'lstm_model.h5', 'lstm_model2.h5', 'merged_df.csv', 'merged_df2.csv', 'Predicting site with anomalies data.ipynb', 'README.md', 'requirements.txt', 'scaler.pkl', 'scaler2.pkl']