In [33]:
import pandas as pd
import numpy as np

df = pd.read_excel("C:/Users/admin/Downloads/jalaram_25march.xlsx", header=8)
df.head()

,PROJECT_NAME,TIMESTAMP,PM2.5,PM10,TEMPERATURE,HUMIDITY
0,Jalaram developer,2026-03-25T00:00:29+05:30,89.375,88.375,29.1,79.8
1,Jalaram developer,2026-03-25T00:00:59+05:30,90.325,88.325,29.1,79.8
2,Jalaram developer,2026-03-25T00:01:29+05:30,91.325,85.325,29.1,79.8
3,Jalaram developer,2026-03-25T00:01:59+05:30,89.325,89.325,29.1,79.7
4,Jalaram developer,2026-03-25T00:02:29+05:30,90.775,88.775,29.1,79.6

In [34]:
#Converting from timestamp to datetime
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'], format='mixed')

In [35]:
#Set Index
df = df.set_index('TIMESTAMP')

In [36]:
#Resample data into 1hour batch
sensor_df = df.resample('1h').mean(numeric_only=True)

In [37]:
#Checking  Type of Index
print(type(df.index))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [38]:
#Interpolate: to replace with mode value of any  columns
sensor_df = sensor_df.interpolate(limit_direction='forward')

In [39]:
#Round-Of Data
sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']] = sensor_df[['PM2.5','PM10','TEMPERATURE','HUMIDITY']].round(2)

In [40]:
#Reset Index
sensor_df = sensor_df.reset_index()

In [42]:
sensor_df.head(20)

                   TIMESTAMP  PM2.5   PM10  TEMPERATURE  HUMIDITY
0  2026-03-25 00:00:00+05:30  88.44  88.72        28.96     75.06
1  2026-03-25 01:00:00+05:30  88.41  88.26        28.77     73.65
2  2026-03-25 02:00:00+05:30  88.22  88.52        28.47     76.51
3  2026-03-25 03:00:00+05:30  88.28  88.23        28.23     78.13
4  2026-03-25 04:00:00+05:30  88.13  88.27        28.08     82.61
5  2026-03-25 05:00:00+05:30  88.48  88.71        27.96     83.14
6  2026-03-25 06:00:00+05:30  87.94  88.02        27.84     81.31
7  2026-03-25 07:00:00+05:30  88.37  88.30        28.50     75.59
8  2026-03-25 08:00:00+05:30  88.70  88.44        30.60     66.38
9  2026-03-25 09:00:00+05:30  88.31  88.44        32.82     58.45
10 2026-03-25 10:00:00+05:30  88.49  88.20        34.24     54.13
11 2026-03-25 11:00:00+05:30  88.17  88.14        34.92     54.93

Weather Data

In [10]:
#Weather Data 
weather_df = pd.read_excel("C:/Users/admin/Downloads/vileparle_east.xlsx", header=16)
weather_df

,From Date,To Date,Ozone,RH,WS,WD,SR,BP,AT,RF,CO
0,01-01-2026 00:00,01-01-2026 01:00,NaN,99.90,1.48,19.61,79.24,1011.46,27.89,NaN,1.13
1,01-01-2026 01:00,01-01-2026 02:00,NaN,99.90,1.56,24.66,79.24,1011.17,27.90,NaN,1.16
2,01-01-2026 02:00,01-01-2026 03:00,NaN,99.90,2.21,63.98,79.24,1010.92,27.89,NaN,1.17
3,01-01-2026 03:00,01-01-2026 04:00,NaN,99.90,2.22,64.11,79.24,1010.58,27.89,NaN,1.19
4,01-01-2026 04:00,01-01-2026 05:00,NaN,99.89,2.22,94.15,79.24,1010.45,27.90,NaN,1.21
...,...,...,...,...,...,...,...,...,...,...,...
1981,24-03-2026 13:00,24-03-2026 14:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.63
1982,24-03-2026 14:00,24-03-2026 15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.62
1983,24-03-2026 15:00,24-03-2026 16:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.62
1984,24-03-2026 16:00,24-03-2026 17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.62
1985,24-03-2026 17:00,24-03-2026 17:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.62

In [11]:
#Remode To Date Columns
weather_df = weather_df.drop('To Date',axis=1)

In [12]:
weather_df.set_index('From Date')

                  Ozone     RH    WS     WD     SR       BP     AT  RF    CO
From Date
01-01-2026 00:00    NaN  99.90  1.48  19.61  79.24  1011.46  27.89 NaN  1.13
01-01-2026 01:00    NaN  99.90  1.56  24.66  79.24  1011.17  27.90 NaN  1.16
01-01-2026 02:00    NaN  99.90  2.21  63.98  79.24  1010.92  27.89 NaN  1.17
01-01-2026 03:00    NaN  99.90  2.22  64.11  79.24  1010.58  27.89 NaN  1.19
01-01-2026 04:00    NaN  99.89  2.22  94.15  79.24  1010.45  27.90 NaN  1.21
...                 ...    ...   ...    ...    ...      ...    ...  ..   ...
24-03-2026 13:00    NaN    NaN   NaN    NaN    NaN      NaN    NaN NaN  0.63
24-03-2026 14:00    NaN    NaN   NaN    NaN    NaN      NaN    NaN NaN  0.62
24-03-2026 15:00    NaN    NaN   NaN    NaN    NaN      NaN    NaN NaN  0.62
24-03-2026 16:00    NaN    NaN   NaN    NaN    NaN      NaN    NaN NaN  0.62
24-03-2026 17:00    NaN    NaN   NaN    NaN    NaN      NaN    NaN NaN  0.62

[1986 rows x 9 columns]

In [13]:
#Replace From Date to TIMESTAMP
weather_df.rename(columns={'From Date':'TIMESTAMP'}, inplace=True)

In [14]:
weather_df = weather_df.set_index('TIMESTAMP')

In [15]:
#Making Timestamp same
sensor_df['TIMESTAMP'] = sensor_df['TIMESTAMP'].dt.tz_localize(None)
#print(sensor_df.columns)
#sensor_df.head()

In [16]:
print(weather_df.columns)

Index(['Ozone', 'RH', 'WS', 'WD', 'SR', 'BP', 'AT', 'RF', 'CO'], dtype='object')

In [27]:
weather_df.tail(50)

               TIMESTAMP  RH  WS  WD  SR  BP  AT  RF    CO
1936 2026-03-22 16:00:00 NaN NaN NaN NaN NaN NaN NaN  0.59
1937 2026-03-22 17:00:00 NaN NaN NaN NaN NaN NaN NaN  0.58
1938 2026-03-22 18:00:00 NaN NaN NaN NaN NaN NaN NaN  0.58
1939 2026-03-22 19:00:00 NaN NaN NaN NaN NaN NaN NaN  0.58
1940 2026-03-22 20:00:00 NaN NaN NaN NaN NaN NaN NaN  0.58
1941 2026-03-22 21:00:00 NaN NaN NaN NaN NaN NaN NaN  0.57
1942 2026-03-22 22:00:00 NaN NaN NaN NaN NaN NaN NaN  0.57
1943 2026-03-22 23:00:00 NaN NaN NaN NaN NaN NaN NaN  0.57
1944 2026-03-23 00:00:00 NaN NaN NaN NaN NaN NaN NaN  0.57
1945 2026-03-23 01:00:00 NaN NaN NaN NaN NaN NaN NaN  0.57
1946 2026-03-23 02:00:00 NaN NaN NaN NaN NaN NaN NaN  0.60
1947 2026-03-23 03:00:00 NaN NaN NaN NaN NaN NaN NaN  0.61
1948 2026-03-23 04:00:00 NaN NaN NaN NaN NaN NaN NaN  0.62
1949 2026-03-23 05:00:00 NaN NaN NaN NaN NaN NaN NaN  0.62
1950 2026-03-23 06:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1951 2026-03-23 07:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1952 2026-03-23 08:00:00 NaN NaN NaN NaN NaN NaN NaN  0.64
1953 2026-03-23 09:00:00 NaN NaN NaN NaN NaN NaN NaN  0.65
1954 2026-03-23 10:00:00 NaN NaN NaN NaN NaN NaN NaN  0.66
1955 2026-03-23 11:00:00 NaN NaN NaN NaN NaN NaN NaN  0.67
1956 2026-03-23 12:00:00 NaN NaN NaN NaN NaN NaN NaN  0.67
1957 2026-03-23 13:00:00 NaN NaN NaN NaN NaN NaN NaN  0.67
1958 2026-03-23 14:00:00 NaN NaN NaN NaN NaN NaN NaN  0.67
1959 2026-03-23 15:00:00 NaN NaN NaN NaN NaN NaN NaN  0.67
1960 2026-03-23 16:00:00 NaN NaN NaN NaN NaN NaN NaN  0.66
1961 2026-03-23 17:00:00 NaN NaN NaN NaN NaN NaN NaN  0.66
1962 2026-03-23 18:00:00 NaN NaN NaN NaN NaN NaN NaN  0.65
1963 2026-03-23 19:00:00 NaN NaN NaN NaN NaN NaN NaN  0.64
1964 2026-03-23 20:00:00 NaN NaN NaN NaN NaN NaN NaN  0.64
1965 2026-03-23 21:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1966 2026-03-23 22:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1967 2026-03-23 23:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1968 2026-03-24 00:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1969 2026-03-24 01:00:00 NaN NaN NaN NaN NaN NaN NaN  0.64
1970 2026-03-24 02:00:00 NaN NaN NaN NaN NaN NaN NaN  0.64
1971 2026-03-24 03:00:00 NaN NaN NaN NaN NaN NaN NaN  0.64
1972 2026-03-24 04:00:00 NaN NaN NaN NaN NaN NaN NaN  0.64
1973 2026-03-24 05:00:00 NaN NaN NaN NaN NaN NaN NaN  0.64
1974 2026-03-24 06:00:00 NaN NaN NaN NaN NaN NaN NaN  0.64
1975 2026-03-24 07:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1976 2026-03-24 08:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1977 2026-03-24 09:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1978 2026-03-24 10:00:00 NaN NaN NaN NaN NaN NaN NaN  0.62
1979 2026-03-24 11:00:00 NaN NaN NaN NaN NaN NaN NaN  0.62
1980 2026-03-24 12:00:00 NaN NaN NaN NaN NaN NaN NaN  0.62
1981 2026-03-24 13:00:00 NaN NaN NaN NaN NaN NaN NaN  0.63
1982 2026-03-24 14:00:00 NaN NaN NaN NaN NaN NaN NaN  0.62
1983 2026-03-24 15:00:00 NaN NaN NaN NaN NaN NaN NaN  0.62
1984 2026-03-24 16:00:00 NaN NaN NaN NaN NaN NaN NaN  0.62
1985 2026-03-24 17:00:00 NaN NaN NaN NaN NaN NaN NaN  0.62

In [18]:
weather_df = weather_df.reset_index()

In [19]:
weather_df['TIMESTAMP'] = pd.to_datetime(
    weather_df['TIMESTAMP'],
    format='%d-%m-%Y %H:%M'
)

In [20]:
weather_df.head()

,TIMESTAMP,Ozone,RH,WS,WD,SR,BP,AT,RF,CO
0,2026-01-01 00:00:00,NaN,99.90,1.48,19.61,79.24,1011.46,27.89,NaN,1.13
1,2026-01-01 01:00:00,NaN,99.90,1.56,24.66,79.24,1011.17,27.90,NaN,1.16
2,2026-01-01 02:00:00,NaN,99.90,2.21,63.98,79.24,1010.92,27.89,NaN,1.17
3,2026-01-01 03:00:00,NaN,99.90,2.22,64.11,79.24,1010.58,27.89,NaN,1.19
4,2026-01-01 04:00:00,NaN,99.89,2.22,94.15,79.24,1010.45,27.90,NaN,1.21

In [21]:
weather_df = weather_df.drop('Ozone',axis=1)

In [22]:
weather_df.head()

            TIMESTAMP     RH    WS     WD     SR       BP     AT  RF    CO
0 2026-01-01 00:00:00  99.90  1.48  19.61  79.24  1011.46  27.89 NaN  1.13
1 2026-01-01 01:00:00  99.90  1.56  24.66  79.24  1011.17  27.90 NaN  1.16
2 2026-01-01 02:00:00  99.90  2.21  63.98  79.24  1010.92  27.89 NaN  1.17
3 2026-01-01 03:00:00  99.90  2.22  64.11  79.24  1010.58  27.89 NaN  1.19
4 2026-01-01 04:00:00  99.89  2.22  94.15  79.24  1010.45  27.90 NaN  1.21

In [23]:
#Merge Data So our ML model can train
merged_df = pd.merge(sensor_df,weather_df, on="TIMESTAMP")

In [24]:
merged_df = merged_df.dropna()

In [25]:
merged_df.size

0